# Generated by Django 4.2.3 on 2023-07-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category_name',
            new_name='category',
        ),
    ]
