# Generated by Django 4.2.3 on 2023-07-13 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_category_name_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='marks',
        ),
        migrations.CreateModel(
            name='ItemMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mark', models.CharField(max_length=1000)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
