# Generated by Django 4.2.3 on 2023-07-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_fio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='photo',
            field=models.ImageField(upload_to='media/marks', verbose_name='Изображение фотки'),
        ),
    ]
