# Generated by Django 4.2.3 on 2023-07-13 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_item_marks_itemmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmark',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='api.item'),
        ),
    ]
