# Generated by Django 4.2.3 on 2023-07-14 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_category_item_remove_producer_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0.0, verbose_name='Баланс'),
        ),
    ]
