# Generated by Django 4.2.3 on 2023-07-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=255, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, verbose_name='Долгота'),
        ),
    ]
