# Generated by Django 4.2.3 on 2023-07-16 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_balance_alter_user_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=200, verbose_name='Номер машины')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорты',
            },
        ),
        migrations.AddField(
            model_name='producer',
            name='condition',
            field=models.CharField(default='', max_length=500, verbose_name='Условия распознования'),
        ),
        migrations.AddField(
            model_name='producer',
            name='passenger',
            field=models.BooleanField(default=False, verbose_name='Легковой'),
        ),
        migrations.AddField(
            model_name='producer',
            name='truck',
            field=models.BooleanField(default=False, verbose_name='Грузовой'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.ForeignKey(on_delete=models.SET(0), to='api.producer', verbose_name='Производитель')),
                ('carNumber', models.ForeignKey(on_delete=models.SET(0), to='api.car', verbose_name='Номер машины')),
                ('user', models.ForeignKey(on_delete=models.SET(0), to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mark', models.CharField(max_length=500, verbose_name='Код')),
                ('photo', models.CharField(max_length=1000, verbose_name='Код фотки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='api.order')),
            ],
            options={
                'verbose_name': 'Уникальный код',
                'verbose_name_plural': 'Уникальные коды',
            },
        ),
    ]
